name: DataHyve CLI CD

on:
  push:
    branches:
      - main
      - issue-1
#     paths:
#       - 'cli/**' 
#   pull_request:
#     paths:
#       - 'cli/**' 

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        working-directory: cli  
        run: |
          poetry install

  deploy:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      - name: Install dependencies
        working-directory: cli
        run: |
          poetry install

      - name: Build and Publish to PyPI
        working-directory: cli  
        run: |
          poetry version patch
          poetry build
          poetry publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  

      - name: Notify success
        run: echo "Deployment successful!"
